### ISSUE TITLE
prusa xl different heads different y positions

### ISSUE THREAD

**Issue by mogorman** [jneilliii/OctoPrint-PrusaFilamentRunoutMonitor#1]
i have a dual head prusa xl, it puts the -y position for one head at -6.6 and the other at -7.  so the single value wouldnt work for me.

I did work around it like this if anyone else is interested

```yaml
mqtt:
  binary_sensor:
    - name: "Printer Out of Filament"
      state_topic: "octoprint/event/PositionUpdate"
      value_template: "{%if value_json.z | float > 0.2 and value_json.y | float  < -4.0 %}ON{%- else -%}OFF{%-endif%}"
      unique_id: "printer_out_filament"
      device:
        identifiers:
          - "OctoPrint"
        name: "OctoPrint"
```

I think you could do something similar in your code as well anything deep into the negative is the out filament move in my testing at least.
